[target.aarch64-apple-ios]
rustflags = []

[env]
PKG_CONFIG_ALLOW_CROSS = "1"
GLIB_2_0_NO_PKG_CONFIG = "1"  # Using underscore instead of period
GOBJECT_2_0_NO_PKG_CONFIG = "1"  # Using underscore instead of period
GIO_2_0_NO_PKG_CONFIG = "1"  # Using underscore instead of period
