export const MOTDS = [
    'jrnl.fm',
    'Endless - Frank Ocean',
    'Balloonerism - Mac Miller',
    'Figure out any cheat codes yet?',
    'If you see this that means I finished an app',
    'Vue is my favorite frontend framework',
    '👋 - Cooper',
    'Did this make it on the app store?',
    'You shouldn\'t have time to read this much text before the app loads',
    '🫵YOU',
    'DIAMONDZ N CASH - Kevin Abstract',
    'CITY IN THE SKY - ye',
    'American Boyfriend: A Suburban Love Story - Kevin Abstract',
    'READY FOR WAR - BROCKHAMPTON',
    'Degas Park - Kevin Abstract',
    'These Days - Frank Ocean',
    'Nikes - Frank Ocean',
    'Ivy - Frank Ocean',
    'Genevieve - Jai Paul',
    'I got rejected from UMD',
    'Walt Whitman High School future graduate',
    'I should probably spend my time writing rhymes in the dentist\'s office; that\'s killing two birds in one stone',
    'Please hire me www.cooperhanessian.com',
    'LOOK AT US, WE\'RE IN LOVE',
    'Teach Me Empathy',
    'Thanks JetBrains'
] as const;