export const MOTDS = [
    'jrnl.fm',
    'Endless - Frank Ocean',
    'DJ\'s Chord Organ - Mac Miller',
    'Figure out any cheat codes yet?',
    'If you see this that means I finished an app',
    'Vue is my favorite frontend framework',
    '👋 - Cooper',
    'Did this make it on the app store?',
    'You shouldn\'t have time to read this much text before the app loads unless something went very wrong',
    '🫵YOU',
    'DIAMONDZ N CASH - Kevin Abstract',
    'CITY IN THE SKY - Kanye West',
    'American Boyfriend: A Suburban Love Story - Kevin Abstract',
    'READY FOR WAR - BROCKHAMPTON',
    'Degas Park - Kevin Abstract',
    'These Days - Frank Ocean',
    'Nikes - Frank Ocean',
    'Ivy - Frank Ocean',
    'Genevieve - Jai Paul',
    'At Your Best (You Are Love) - Aaliyah',
    'I got rejected from UMD',
    'Walt Whitman High School future graduate',
    'I should probably spend my time writing rhymes in the dentist\'s office; that\'s killing two birds in one stone',
    'Please hire me www.cooperhanessian.com',
    'LOOK AT US, WE\'RE IN LOVE',
    'Teach Me Empathy',
    'Thanks JetBrains',
    'Leak 04-13 (Bait Ones) - Jai Paul',
    'RIP CAPITAL STEEZ',
    'Little Dominiques Nosebleed - The Koreatown Oddity',
    'Sideways - Frank Ocean',
    'VOIR DIRE - Earl Sweatshirt, The Alchemist',
    'Home - Portraits of Tracy',
    'Brain Cells - Chance the Rapper',
    'Ipari Park - MIKE',
    'Come My Way - Saba',
    'SMUCKERS - Tyler, The Creator',
    'Me and Your Mama - Childish Gambino',
    'Spaceship - Kanye West',
    'Guilt Trip - Kanye West',
    'cooperhanessian.com <-- That\'s me!',
    'Bruiseboy - Jean Dawson',
    'Hi8 tapes don\'t last forever',
    'one two two one three'
] as const;